name: simple-cprog
base: core18
version: '1.0.0'
summary: Simple C Prog
description: |
  Simple C Prog
grade: stable
confinement: strict
architectures:
  - build-on: amd64

apps:
  runhello:
     command: /snap/simple-cprog/current/a.out

  
parts:
  cprog:
    source: https://github.com/drunkenlord/c-test/releases/download/v1.0.0/cprog1.tar.gz
    plugin: dump
